"use client";

import { forwardRef, useMemo } from "react";
import DOMPurify from "dompurify";
import type { TileGrid, PrintConfig } from "./print-utils";
import {
  generateCropMarks,
  generatePageLabel,
  getPrintableArea,
} from "./print-utils";

interface PosterPrintViewProps {
  /** The SVG content of the diagram (inner content, not full SVG element) */
  diagramSvgContent: string;
  /** The full diagram bounds for viewBox calculation */
  diagramBounds: { x: number; y: number; width: number; height: number };
  /** Tile grid configuration */
  tileGrid: TileGrid;
  /** Print configuration */
  config: PrintConfig;
  /** Whether to show crop marks */
  showCropMarks: boolean;
  /** Optional title for page labels */
  diagramTitle?: string;
}

/**
 * Sanitize SVG content for safe rendering.
 * Allows SVG-specific elements and attributes needed for diagram rendering.
 */
function sanitizeSvgContent(content: string): string {
  return DOMPurify.sanitize(content, {
    USE_PROFILES: { svg: true, svgFilters: true },
    ADD_TAGS: ["foreignObject"],
    ADD_ATTR: [
      "transform",
      "viewBox",
      "preserveAspectRatio",
      "xmlns",
      "xmlns:xlink",
    ],
  });
}

/**
 * Poster print view that renders the diagram across multiple tiled pages.
 * Each tile shows a portion of the diagram with optional crop marks for alignment.
 */
export const PosterPrintView = forwardRef<HTMLDivElement, PosterPrintViewProps>(
  function PosterPrintView(
    {
      diagramSvgContent,
      diagramBounds,
      tileGrid,
      config,
      showCropMarks,
      diagramTitle,
    },
    ref
  ) {
    const printable = getPrintableArea(
      config.paperSize,
      config.orientation,
      config.margins
    );

    // Sanitize the SVG content once for all tiles
    const sanitizedContent = useMemo(
      () => sanitizeSvgContent(diagramSvgContent),
      [diagramSvgContent]
    );

    return (
      <div ref={ref} className="poster-print-container bg-white">
        {tileGrid.tiles.map((tile) => (
          <PosterTile
            key={`tile-${tile.row}-${tile.col}`}
            tile={tile}
            tileGrid={tileGrid}
            diagramSvgContent={sanitizedContent}
            diagramBounds={diagramBounds}
            config={config}
            printable={printable}
            showCropMarks={showCropMarks}
            diagramTitle={diagramTitle}
          />
        ))}
      </div>
    );
  }
);

interface PosterTileProps {
  tile: TileGrid["tiles"][0];
  tileGrid: TileGrid;
  diagramSvgContent: string;
  diagramBounds: { x: number; y: number; width: number; height: number };
  config: PrintConfig;
  printable: { width: number; height: number };
  showCropMarks: boolean;
  diagramTitle: string | undefined;
}

function PosterTile({
  tile,
  tileGrid,
  diagramSvgContent,
  config,
  printable,
  showCropMarks,
  diagramTitle,
}: PosterTileProps) {
  // Generate crop marks SVG (already trusted content from our utility)
  const cropMarksSvg = useMemo(() => {
    if (!showCropMarks) return null;
    return generateCropMarks(tile, tileGrid, config);
  }, [tile, tileGrid, config, showCropMarks]);

  // Generate page label
  const pageLabel = useMemo(() => {
    const label = generatePageLabel(tile, tileGrid);
    return diagramTitle ? `${diagramTitle} • ${label}` : label;
  }, [tile, tileGrid, diagramTitle]);

  // The viewBox for this tile's portion of the diagram
  const { viewBox } = tile;

  return (
    <div
      className="poster-tile"
      style={{
        position: "relative",
        width: "100%",
        height: "100vh",
        overflow: "hidden",
        pageBreakAfter: "always",
        boxSizing: "border-box",
      }}
    >
      {/* Tile content - the diagram portion */}
      <div
        className="tile-content"
        style={{
          position: "absolute",
          top: `${config.margins}mm`,
          left: `${config.margins}mm`,
          width: `${printable.width}mm`,
          height: `${printable.height}mm`,
          overflow: "hidden",
        }}
      >
        <svg
          viewBox={`${viewBox.x} ${viewBox.y} ${viewBox.width} ${viewBox.height}`}
          preserveAspectRatio="xMidYMid meet"
          style={{
            width: "100%",
            height: "100%",
            backgroundColor: "white",
          }}
        >
          <g dangerouslySetInnerHTML={{ __html: diagramSvgContent }} />
        </svg>
      </div>

      {/* Crop marks overlay - trusted content generated by our utility */}
      {showCropMarks && cropMarksSvg && (
        <div
          className="crop-marks-layer"
          style={{
            position: "absolute",
            top: `${config.margins}mm`,
            left: `${config.margins}mm`,
            width: `${printable.width}mm`,
            height: `${printable.height}mm`,
            pointerEvents: "none",
          }}
          dangerouslySetInnerHTML={{ __html: cropMarksSvg }}
        />
      )}

      {/* Page label */}
      <div
        className="page-label"
        style={{
          position: "absolute",
          bottom: "5mm",
          left: "50%",
          transform: "translateX(-50%)",
          fontSize: "8pt",
          color: "#666",
          fontFamily: "system-ui, sans-serif",
          whiteSpace: "nowrap",
        }}
      >
        {pageLabel}
      </div>
    </div>
  );
}

/**
 * Preview component showing the tile grid layout.
 * Used in the print dialog to visualize how pages will be arranged.
 */
export function TileGridPreview({
  tileGrid,
  orientation,
}: {
  tileGrid: TileGrid;
  orientation: "portrait" | "landscape";
}) {
  return (
    <div
      className="tile-grid-preview"
      style={{
        display: "grid",
        gridTemplateColumns: `repeat(${tileGrid.cols}, 1fr)`,
        gap: "2px",
        maxWidth: "200px",
      }}
    >
      {tileGrid.tiles.map((tile) => (
        <div
          key={tile.pageNumber}
          className={`tile-cell ${orientation}`}
          style={{
            aspectRatio: orientation === "landscape" ? "11 / 8.5" : "8.5 / 11",
            background: "white",
            border: "1px solid #d1d5db",
            borderRadius: "2px",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            fontSize: "10px",
            color: "#9ca3af",
          }}
        >
          {tile.pageNumber}
        </div>
      ))}
    </div>
  );
}

export default PosterPrintView;
